# TCL File Generated by Component Editor 22.1
# Fri Sep 19 23:34:13 PDT 2025
# DO NOT MODIFY


# 
# controller_uart_bridge "controller_uart_bridge" v1.0
#  2025.09.19.23:34:13
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module controller_uart_bridge
# 
set_module_property DESCRIPTION ""
set_module_property NAME controller_uart_bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Personal Bridges"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME controller_uart_bridge
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ControllerState
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ControllerState.sv SYSTEM_VERILOG PATH ControllerState.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point interrupt_receiver
# 
add_interface interrupt_receiver interrupt start
set_interface_property interrupt_receiver associatedAddressablePoint uart_master
set_interface_property interrupt_receiver associatedClock clock
set_interface_property interrupt_receiver associatedReset reset_sink
set_interface_property interrupt_receiver irqScheme INDIVIDUAL_REQUESTS
set_interface_property interrupt_receiver ENABLED true
set_interface_property interrupt_receiver EXPORT_OF ""
set_interface_property interrupt_receiver PORT_NAME_MAP ""
set_interface_property interrupt_receiver CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_receiver SVD_ADDRESS_GROUP ""

add_interface_port interrupt_receiver irq irq Input 1


# 
# connection point uart_master
# 
add_interface uart_master avalon start
set_interface_property uart_master addressUnits WORDS
set_interface_property uart_master associatedClock clock
set_interface_property uart_master associatedReset reset_sink
set_interface_property uart_master bitsPerSymbol 8
set_interface_property uart_master burstOnBurstBoundariesOnly false
set_interface_property uart_master burstcountUnits WORDS
set_interface_property uart_master doStreamReads false
set_interface_property uart_master doStreamWrites false
set_interface_property uart_master holdTime 0
set_interface_property uart_master linewrapBursts false
set_interface_property uart_master maximumPendingReadTransactions 0
set_interface_property uart_master maximumPendingWriteTransactions 0
set_interface_property uart_master readLatency 1
set_interface_property uart_master readWaitTime 0
set_interface_property uart_master setupTime 0
set_interface_property uart_master timingUnits Cycles
set_interface_property uart_master writeWaitTime 0
set_interface_property uart_master ENABLED true
set_interface_property uart_master EXPORT_OF ""
set_interface_property uart_master PORT_NAME_MAP ""
set_interface_property uart_master CMSIS_SVD_VARIABLES ""
set_interface_property uart_master SVD_ADDRESS_GROUP ""

add_interface_port uart_master m_write_data writedata Output 32
add_interface_port uart_master m_write write Output 1
add_interface_port uart_master m_address address Output 3
add_interface_port uart_master m_byte_enable byteenable Output 4
add_interface_port uart_master m_cs chipselect Output 1
add_interface_port uart_master m_read read Output 1
add_interface_port uart_master m_read_data readdata Input 32


# 
# connection point cpu_slave
# 
add_interface cpu_slave avalon end
set_interface_property cpu_slave addressUnits WORDS
set_interface_property cpu_slave associatedClock clock
set_interface_property cpu_slave associatedReset reset_sink
set_interface_property cpu_slave bitsPerSymbol 8
set_interface_property cpu_slave burstOnBurstBoundariesOnly false
set_interface_property cpu_slave burstcountUnits WORDS
set_interface_property cpu_slave explicitAddressSpan 0
set_interface_property cpu_slave holdTime 0
set_interface_property cpu_slave linewrapBursts false
set_interface_property cpu_slave maximumPendingReadTransactions 0
set_interface_property cpu_slave maximumPendingWriteTransactions 0
set_interface_property cpu_slave readLatency 0
set_interface_property cpu_slave readWaitStates 0
set_interface_property cpu_slave readWaitTime 0
set_interface_property cpu_slave setupTime 0
set_interface_property cpu_slave timingUnits Cycles
set_interface_property cpu_slave writeWaitTime 0
set_interface_property cpu_slave ENABLED true
set_interface_property cpu_slave EXPORT_OF ""
set_interface_property cpu_slave PORT_NAME_MAP ""
set_interface_property cpu_slave CMSIS_SVD_VARIABLES ""
set_interface_property cpu_slave SVD_ADDRESS_GROUP ""

add_interface_port cpu_slave s_cs chipselect Input 1
add_interface_port cpu_slave s_read_data readdata Output 8
add_interface_port cpu_slave s_address address Input 1
add_interface_port cpu_slave s_read read Input 1
set_interface_assignment cpu_slave embeddedsw.configuration.isFlash 0
set_interface_assignment cpu_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment cpu_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment cpu_slave embeddedsw.configuration.isPrintableDevice 0

